import { CodeLanguages } from "@/types";

const CodeLanguages: CodeLanguages = {
    "1c": "1C",
    "4d": "4D",
    "abnf": "ABNF",
    "accesslog": "Access Log",
    "actionscript": "ActionScript",
    "ada": "Ada",
    "adoscript": "AdoScript",
    "apache": "Apache",
    "apacheaccess": "Apache Access",
    "applescript": "AppleScript",
    "arduino": "Arduino",
    "armasm": "ARM Assembly",
    "asciidoc": "AsciiDoc",
    "aspectj": "AspectJ",
    "asn1": "ASN.1",
    "autohotkey": "AutoHotkey",
    "autoit": "AutoIt",
    "avrasm": "AVR Assembly",
    "awk": "AWK",
    "axapta": "Axapta",
    "bash": "Bash",
    "basic": "BASIC",
    "bf": "Brainfuck",
    "bibtex": "BibTeX",
    "blitzbasic": "Blitz BASIC",
    "bnf": "BNF",
    "brainfuck": "Brainfuck",
    "c": "C",
    "cal": "CAL",
    "capnproto": "Cap'n Proto",
    "cbml": "CBML",
    "cbmbasicv2": "CBM BASIC V2",
    "cddl": "CDDL",
    "ceylon": "Ceylon",
    "clean": "Clean",
    "clojure": "Clojure",
    "cmake": "CMake",
    "coq": "Coq",
    "cos": "COS",
    "cpp": "C++",
    "crmsh": "crmsh",
    "crystal": "Crystal",
    "csharp": "C#",
    "csound": "Csound",
    "css": "CSS",
    "d": "D",
    "dart": "Dart",
    "delphi": "Delphi",
    "diff": "Diff",
    "django": "Django",
    "dns": "DNS",
    "dockerfile": "Dockerfile",
    "dos": "DOS",
    "dsconfig": "dsconfig",
    "dts": "DTS",
    "dust": "Dust",
    "ebnf": "EBNF",
    "elixir": "Elixir",
    "elm": "Elm",
    "erb": "ERB",
    "erlang": "Erlang",
    "excel": "Excel",
    "fsharp": "F#",
    "fix": "FIX",
    "flix": "Flix",
    "fortran": "Fortran",
    "freepascal": "Free Pascal",
    "fsl": "FSL",
    "gams": "GAMS",
    "gauss": "GAUSS",
    "gcode": "G-code",
    "gherkin": "Gherkin",
    "glsl": "GLSL",
    "gml": "GML",
    "gn": "GN",
    "gni": "GNI",
    "go": "Go",
    "golo": "Golo",
    "gradle": "Gradle",
    "graphql": "GraphQL",
    "groovy": "Groovy",
    "gss": "GSS",
    "haml": "Haml",
    "handlebars": "Handlebars",
    "haskell": "Haskell",
    "haxe": "Haxe",
    "hsp": "HSP",
    "htmlbars": "HTMLBars",
    "http": "HTTP",
    "hy": "Hy",
    "inform7": "Inform 7",
    "ini": "INI",
    "ino": "Arduino",
    "irpf90": "IRPF90",
    "isbl": "ISBL",
    "java": "Java",
    "javascript": "JavaScript",
    "jboss": "JBoss",
    "json": "JSON",
    "julia": "Julia",
    "kotlin": "Kotlin",
    "lasso": "Lasso",
    "latex": "LaTeX",
    "ldif": "LDIF",
    "leaf": "Leaf",
    "less": "Less",
    "lisp": "Lisp",
    "livecodeserver": "LiveCode",
    "livescript": "LiveScript",
    "llvm": "LLVM",
    "lsl": "LSL",
    "lua": "Lua",
    "magma": "Magma",
    "makefile": "Makefile",
    "markdown": "Markdown",
    "mathematica": "Mathematica",
    "matlab": "MATLAB",
    "maxima": "Maxima",
    "mediawiki": "MediaWiki",
    "mel": "MEL",
    "mercury": "Mercury",
    "mipsasm": "MIPS Assembly",
    "mizar": "Mizar",
    "mojolicious": "Mojolicious",
    "monkey": "Monkey",
    "moonscript": "MoonScript",
    "n1ql": "N1QL",
    "nestedtext": "NestedText",
    "never": "Never",
    "nginx": "Nginx",
    "nim": "Nim",
    "nix": "Nix",
    "node": "Node.js",
    "nusmv": "NuSMV",
    "ocaml": "OCaml",
    "octave": "Octave",
    "objectivec": "Objective-C",
    "openscad": "OpenSCAD",
    "oxygene": "Oxygene",
    "oz": "Oz",
    "pascal": "Pascal",
    "pegjs": "PEG.js",
    "perl": "Perl",
    "php": "PHP",
    "plaintext": "Plain Text",
    "plsql": "PL/SQL",
    "policies": "Policies",
    "pony": "Pony",
    "postscript": "PostScript",
    "powershell": "PowerShell",
    "processing": "Processing",
    "profile": "Profile",
    "prolog": "Prolog",
    "properties": "Properties",
    "protobuf": "Protocol Buffers",
    "puppet": "Puppet",
    "purebasic": "PureBasic",
    "python": "Python",
    "q": "Q",
    "qml": "QML",
    "r": "R",
    "racket": "Racket",
    "reasonml": "ReasonML",
    "rebol": "Rebol",
    "red": "Red",
    "regexp": "RegExp",
    "rel": "REL",
    "renderx": "RenderX",
    "rib": "RIB",
    "roboconf": "Roboconf",
    "robotframework": "Robot Framework",
    "rpf": "RPF",
    "rpm": "RPM",
    "rsl": "RSL",
    "ruby": "Ruby",
    "ruleslanguage": "Rules Language",
    "rust": "Rust",
    "sas": "SAS",
    "scala": "Scala",
    "scheme": "Scheme",
    "scilab": "Scilab",
    "scss": "SCSS",
    "shell": "Shell",
    "smali": "Smali",
    "smalltalk": "Smalltalk",
    "sml": "SML",
    "sqf": "SQF",
    "sql": "SQL",
    "stan": "Stan",
    "stata": "Stata",
    "step21": "STEP 21",
    "stylus": "Stylus",
    "subunit": "SubUnit",
    "svelte": "Svelte",
    "swift": "Swift",
    "taggerscript": "Tagger Script",
    "tagscript": "Tag Script",
    "tap": "TAP",
    "tcl": "Tcl",
    "tex": "TeX",
    "text": "Text",
    "thrift": "Thrift",
    "tiki": "Tiki",
    "tk": "Tk",
    "toml": "TOML",
    "trac": "Trac",
    "tsql": "T-SQL",
    "tt2": "Template Toolkit 2",
    "turtle": "Turtle",
    "twig": "Twig",
    "typescript": "TypeScript",
    "vala": "Vala",
    "vbnet": "VB.NET",
    "vbscript": "VBScript",
    "vbs": "VBScript",
    "vdf": "VDF",
    "verilog": "Verilog",
    "vhdl": "VHDL",
    "vim": "Vim script",
    "wasm": "WebAssembly",
    "wenyan": "Wenyan",
    "wildfly": "WildFly",
    "x86asm": "x86 Assembly",
    "xl": "XL",
    "xml": "XML",
    "xpath": "XPath",
    "xquery": "XQuery",
    "xtend": "Xtend",
    "yaml": "YAML",
    "yang": "YANG",
    "zephir": "Zephir"
};

export default CodeLanguages;