import { CodeLanguages } from '@/types';

const CodeLanguages: CodeLanguages = {
  bash: 'Bash',
  c: 'C',
  clojure: 'Clojure',
  cmake: 'CMake',
  cpp: 'C++',
  csharp: 'C#',
  css: 'CSS',
  dart: 'Dart',
  dockerfile: 'Dockerfile',
  elixir: 'Elixir',
  erlang: 'Erlang',
  fsharp: 'F#',
  go: 'Go',
  graphql: 'GraphQL',
  groovy: 'Groovy',
  haskell: 'Haskell',
  html: 'HTML',
  java: 'Java',
  javascript: 'JavaScript',
  json: 'JSON',
  julia: 'Julia',
  kotlin: 'Kotlin',
  less: 'Less',
  lua: 'Lua',
  makefile: 'Makefile',
  markdown: 'Markdown',
  matlab: 'MATLAB',
  nginx: 'Nginx',
  objectivec: 'Objective-C',
  perl: 'Perl',
  php: 'PHP',
  plaintext: 'Plain Text',
  powershell: 'PowerShell',
  python: 'Python',
  r: 'R',
  ruby: 'Ruby',
  rust: 'Rust',
  scala: 'Scala',
  scss: 'SCSS',
  shell: 'Shell',
  sql: 'SQL',
  swift: 'Swift',
  svelte: 'Svelte',
  toml: 'TOML',
  typescript: 'TypeScript',
  vim: 'Vim script',
  wasm: 'WebAssembly',
  xml: 'XML',
  yaml: 'YAML',
};

export default CodeLanguages;
